package:
  name: pivottablejs-aen-custom
  version: "2.7.0"

source:
  git_url: https://github.com/ContinuumIO/pivottablejs-airgap.git
  git_rev: 14bf7d29b2478a76094ebef396b832acc7f08b70

requirements:
  build:
    - python
  run:
    - python
    - notebook

test:
  imports:
    - pivottablejs

about:
  home: https://github.com/ContinuumIO/pivottablejs
  license: MIT
  summary: 'PivotTable.js integration for Jupyter/IPython Notebook'
