package:
  name: pivottablejs
  version: "0.1.0"

source:
  git_url: https://github.com/ContinuumIO/pivottablejs.git
  git_rev: 51dae6a0d40c7a77fbf7d93749c35484f2cc2ca3

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - notebook

test:
  imports:
    - pivottablejs

about:
  home: https://github.com/ContinuumIO/pivottablejs
  license: MIT
  summary: 'PivotTable.js integration for Jupyter/IPython Notebook'